
* OrgNote: A simple org-mode blog, write blog by org-mode in Emacs

* Get Started

  At first, need to fork OrgNote as =yourname.github.com= repo.

  Thus you can open =yourname.github.com= in brower after wait some minutes. 

  And there is a default blog ready now!

* Post Blog

Steps:
#+begin_quote
#+begin_example
$ git clone git@github.com:yourname/yourname.github.com.git

$ python orgnote.py note newnote

$ python orgnote.py page newnote

$ python orgnote.py generate

$ python orgnote.py server [port]

$ git add file1 file2 ...

$ git push origin master
#+end_example
#+end_quote

=orgnote.py= Usage:
#+begin_quote
#+begin_example
$ python orgnote.py

    Usage:
          python orgnote.py note {notename}           ---- add a org-mode note
          python orgnote.py page {notename}           ---- convert .org to .html

          python orgnote.py generate                  ---- generate all notes
          python orgnote.py server [port]             ---- start web server for review
#+end_example
#+end_quote




* Configure

There is only one program named =orgnote.py=, all configures will apply in this file.

** basic
*** __dirs__

The __dirs__ is a list() and each item is a note-list-file.

*** __title__

The =name/title= of the blog.

*** __author__

The =author= of the blog.

*** __description__

The =description= of the blog.

*** __blog_keywords__

The =keywords= of the blog.

** feature
*** note-list-file

note-list-file example:
#+begin_quote
#+begin_example
 - [[../notes/orgnote.html][OrgNote: public   version] ]
 + [[../notes/orgnote.html][OrgNote: nopublic version] ]
#+end_example
#+end_quote

Note:
- There is a blackspace after =-/+=, this is a format of org-mode.
- If the line beginswith =-=, thus the note will public to homepage of blog.
- If the line beginswith =+=, thus the note will only public to =/public/nopublic.html= 

*** About

Find the function =contain_about=, use update it like:
#+begin_quote
#+begin_example
<p> something </p>
#+end_example
#+end_quote

*** Duoshuo

Find function =duosuo=, and add http://duoshuo.com/ code into it:
#+begin_quote
#+begin_src python
def duosuo():
    return """
    your duoshuo code here!
    """
#+end_src
#+end_quote

*** Weibo

Find function =sidebar_weibo=, and add your weibo's code into it:
#+begin_quote
#+begin_src python
def sidebar_weibo():
     return """
     your weibo code here!
     """
#+end_src
#+end_quote

*** Links

Find function =sidebar_link=, and add links.

*** Latest Blogs

Find function =sidebar_latest=, display latest 10 notes, sample:
#+begin_quote
#+begin_src python
def sidebar_latest(notes=list(), num=10):
#+end_src
#+end_quote

The =num=10= meaning display latest 10 notes default.


* More

- =Emacs= : [[http://www.gnu.org/software/emacs/]]
- =Org-mode= : [[http://orgmode.org/][org-mode]]

Enjoy it! :)





